#ifndef __AD7606_H__
#define __AD7606_H__


//设置过采样
#define AD7606OS0_H		HAL_GPIO_WritePin(GPIOC, GPIO_PIN_5, GPIO_PIN_SET)
#define AD7606OS0_L		HAL_GPIO_WritePin(GPIOC, GPIO_PIN_5, GPIO_PIN_RESET)
#define AD7606OS1_H		HAL_GPIO_WritePin(GPIOC, GPIO_PIN_6, GPIO_PIN_SET)
#define AD7606OS1_L		HAL_GPIO_WritePin(GPIOC, GPIO_PIN_6, GPIO_PIN_RESET)
#define AD7606OS2_H		HAL_GPIO_WritePin(GPIOC, GPIO_PIN_8, GPIO_PIN_SET)
#define AD7606OS2_L		HAL_GPIO_WritePin(GPIOC, GPIO_PIN_6, GPIO_PIN_RESET)

//开始转换
#define AD7606_CONVST_A_H 	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, GPIO_PIN_SET)
#define AD7606_CONVST_A_L 	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, GPIO_PIN_RESET)
#define AD7606_CONVST_B_H 	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_SET)
#define AD7606_CONVST_B_L 	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_RESET)

#define AD7606_SCLK_H 	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_12, GPIO_PIN_SET)
#define AD7606_SCLK_L 	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_12, GPIO_PIN_RESET)
#define AD7606_RESET_H 	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_SET)
#define AD7606_RESET_L 	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_RESET)
#define AD7606_CS_H 	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_SET)
#define AD7606_CS_L 	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_RESET)

#define AD7606_BUSY		HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_9)
#define AD7606_DOUTB	HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_7)
#define AD7606_DOUTA	HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_6)


void AD7606_SETOS(uint8_t osv);
void AD7606_RESET(void);
uint16_t ad7606_ReadBytes(void);
void AD7606_STARTCONV(void);
void Delay(uint32_t nCount) ;
void AD7606_Init(uint8_t os );
void AD7606_RANGE10(float vol_data[]);
#endif
